name: React.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Run ESLint
      id: eslint
      run: npx eslint .

    - run: npm run build --if-present
    - name: Create release ZIP
      run: |
        mkdir release
        zip -r release/project-release.zip build

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: project-release
        path: release/project-release.zip
